on: [push]

jobs:
    st-bbaovanc-git_job:
        runs-on: ubuntu-latest
        name: Build bbaovanc's st fork
        steps:
            - name: Clone AUR repo
              run: |
                  git clone https://aur.archlinux.org/st-bbaovanc-git.git

            - name: Makepkg
              uses: py7hon/arch-makepkg@v0.0.2
              with:
                  path: 'st-bbaovanc-git'

            - name: Upload package
              uses: actions/upload-artifact@v2
              with:
                  name: st-bbaovanc-git/st-bbaovanc-git-package
                  path: st-bbaovanc-git/st-bbaovanc-git*.pkg.*
