on: [push]

jobs:
    st-bbaovanc-git_job:
        runs-on: ubuntu-latest
        name: Build bbaovanc's st fork
        steps:
            - name: Clone AUR repo
              run: |
                  git clone https://aur.archlinux.org/st-bbaovanc-git.git

            - name: Makepkg
              id: makepkg
              uses: smallstep/pkgbuild-action@v1.0.1
              with:
                  pkgdir: 'st-bbaovanc-git'

            - name: Upload package
              uses: actions/upload-artifact@v2
              with:
                  path: ${{ steps.makepkg.outputs.pkgfile0 }}
